title: Ankit Gaur
description: Notes on agentic AI, infrastructure, and engineering.
baseurl: "/myblog"
url: "https://ankitg12.github.io"
github_username: ankitg12

theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%B %-d, %Y"
